### ISSUE TITLE
Is the project still alive? (Planning on PRs for 2 new features...)

### ISSUE THREAD

**Issue by lougreenwood** [stevenwanderski/conditional-field#9]
I have a few modifications I'm planning on submitting PRs for, but before I start work on these I wanted to check that the project is alive and PRs will be considered - my features are:

* Allow conditional with multiple select inputs
    * If used with a select2 in multi mode, the value of the select must be an exact match with the visibility selector - so multiple doesn't match and fails to show the conditional field
* Allow displaying multiple elements for the same visibility condition, something like:
    ```
  visibility: {
    'mothers': '.zappa',
    'mothers': '.beefheart',
    'spiders': '.bowie'
  }
```

**Comment by olssonm** [comment]
Wondering the same thing, and those two additions would be nice.

Your second bullet there though is already possible as it uses standard jQuery-selectors (if I understood your example correctly);

```
visibility: {
    'mothers': '.zappa, .beefheart'
}
```

I myself is trying to figure out how to do:

```
visibility: {
    'mothers': '.zappa',
    'freaks': '.zappa', 
    'spiders': '.bowie'
}
```

I.e. to allow an element to displayed on two or more different inputs.

**Comment by lougreenwood** [comment]
@olssonm That's a good example too - I think I'm also going to need that...

But before that, I need @stevenwanderski to get back to us - I'm planning on paying a freelance dev to add these features, so I need to confirm that the project is alive and my PRs won't sit in limbo. Until then I can't justify spending any $$ on the dev to add these features to this library... :(

**Comment by stevenwanderski** [comment]
Hello! Apologies for my silence - I've been on paternity leave 👶

Happy to review any and all PRs. Also, if I can't keep up with new PRs I'm happy to open this project up to any interested maintainers :)

**Comment by olssonm** [comment]
@stevenwanderski – Glad to hear it. Hope you have a great paternity leave, and congrats too!

@lougreenwood – Don't forget that you can always fork the code and do your own edits too – it's not an overly complicated library either, so I am sure a potential freelancer you hire can make a custom solution quite quickly too =)

**Comment by lougreenwood** [comment]
@stevenwanderski - cool - thanks. Congrats :)

@olssonm - Yep, I just didn't want to fork it without the possibility of merging back in. 

Time to commission some work ;)

**Comment by lougreenwood** [comment]
Hey @stevenwanderski & @olssonm - just a heads up that we've submitted our PRs.

https://github.com/stevenwanderski/conditional-field/pull/10
https://github.com/stevenwanderski/conditional-field/pull/11

@olssonm - I think that https://github.com/stevenwanderski/conditional-field/pull/11 should address your request:

```
visibility: {
    'mothers': '.zappa',
    'freaks': '.zappa', 
    'spiders': '.bowie'
}
```

If you have time, a review would be great :)

**Comment by stevenwanderski** [comment]
I'm having trouble finding time to devote to this project 😕 

Anyone interested in becoming a maintainer? I'm happy to allow merge access to interested folks.

**Comment by carlosreig** [comment]
@stevenwanderski thanks for your library. It's very useful :smile: 

Those 2 new features are great! It would be wonderful to have them  :+1: 

@stevenwanderski is the PR from @lougreenwood working?

**Comment by lougreenwood** [comment]
@stevenwanderski - I'm afraid that even though we've contributed code, the developer I hired to make the changes won't be available to be a maintainer.

I also wouldn't be suitable, since I'm not a JS dev.

Perhaps you could find the time to review this PR, so we can at least get that merged? https://github.com/stevenwanderski/conditional-field/pull/10

https://github.com/stevenwanderski/conditional-field/pull/11 Can be ignored for now, since it needs some changes and I need to re-engage the dev who I paid to do the work...
